### ISSUE TITLE
Error starting the driver service

### ISSUE THREAD

**Issue by vportal** [Kharos102/IOCTLDump#1]
Hello,

I get the error below trying to start the service:

C:\Windows\system32>sc start ioctld
[SC] StartService FAILED 127:

The specified procedure could not be found.

I have compiled the driver with visual studio 2019, v142, SDK 10.0.22000.0 (and WDK) in WIndows 10 21H2. Could you add more details regarding the OS build and SDK/VS version you used?

Thanks. best regards.
Víctor

**Comment by Kharos102** [comment]
This driver targets Windows 11.

You're getting this issue as ExFreePool2 isn't available on your Windows 10 instance I believe (easiest way to check is to compile the driver with your relevant Windows 10 WDK instead of the Windows 11 WDK, it won't compile).

I've updated the code to support Windows 10 (by redirecting ExFreePool2 calls to ExFreePool when 'W10' is defined, see comments in IOCTLDump\Main.cpp)
