### ISSUE TITLE
Compiling for win10

### ISSUE THREAD

**Issue by kafkaesqu3** [Kharos102/IOCTLDump#2]
Im trying to compile this for a Windows 10 machine. I defined the W10 preprocessor directive as instructed, but I cant compile because the redefinition of ExFreePool2 gives me this compiler error: 
"more than once instance of the overloaded function ExFreePool2 matches the argument list
How do i resolve this?

Thanks

**Comment by Kharos102** [comment]
To clarify, the point of defining W10 is because the older Windows 10 SDK doesn't have ExFreePool2, so instead we define it ourselves.

From your error, it sounds like you're using a SDK that does define ExFreePool2 already, which likely means you're not using a Windows 10 SDK (and therefore when you go to run the driver on Windows 10, it'll fail to load), or a new Windows 10 SDK exists with ExFreePool2 now available.

You can test it by compiling without W10 and seeing if you can run the driver on Windows 10, if not then try compiling it with W10 and an older Windows 10 SDK that doesn't define ExFreePool2.
